drop table if exists book_author;
drop table if exists book;
drop table if exists author;
drop table if exists publisher;

create table author (
      id bigint generated by default as identity (start with 1)
    , name varchar(255)
    , primary key (id)
);

create table publisher (
      id bigint generated by default as identity (start with 1)
    , name varchar(255)
    , description varchar(255)
    , primary key (id)
);

create table book (
      id bigint generated by default as identity (start with 1)
    , title varchar(255)
    , publisher_id bigint
    , primary key (id)
    , foreign key (publisher_id) references publisher (id)
);

create table book_author (
      book_id bigint
    , author_id bigint
    , foreign key (book_id) references book (id)
    , foreign key (author_id) references author (id)
);

insert into author(name) values ('George Orwell');
insert into author(name) values ('James Herriot');

insert into publisher(name, description) values ('Könyvfakasztó', 'Részletes leírás');

insert into book(title, publisher_id) values ('1984', 1);
insert into book_author(book_id, author_id) values (1, 1);

insert into book(title, publisher_id) values ('Állatorvosi pályám kezdetén', 1);
insert into book_author(book_id, author_id) values (2, 2);
